baseURL: "https://huangf06.github.io/FeiThink/"
languageCode: en-us
title: "FeiThink"
theme: PaperMod

pagination:
  pagerSize: 10

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "FeiThink"
  description: "Personal blog about philosophy, technology, and life"
  keywords: [blog, philosophy, technology, life, essays, writing, thinking]
  author: "Huang Fei"

  # Theme settings
  defaultTheme: auto # auto, light, dark
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: false
    disableFingerprinting: false
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"

  label:
    text: "FeiThink"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # Profile mode (for homepage)
  profileMode:
    enabled: true
    title: "FeiThink"
    subtitle: "Thoughts on philosophy, technology, and life"
    imageUrl: "" # Optional profile image
    imageWidth: 120
    imageHeight: 120
    imageTitle: "Profile"
    buttons:
      - name: Posts
        url: /posts/
      - name: Archives
        url: /archives/
      - name: Tags
        url: /tags/

  # Home Info mode (alternative to profile mode)
  homeInfoParams:
    Title: "Welcome to FeiThink"
    Content: |
      A place for exploring philosophy, technology, and the human experience.

      Feel free to explore my posts or browse by tags.

  socialIcons:
    - name: github
      url: "https://github.com/huangf06"
    - name: linkedin
      url: "https://linkedin.com/in/yourusername"
    - name: email
      url: "mailto:your.email@example.com"
    - name: rss
      url: "/index.xml"

  # Analytics (uncomment and configure when ready)
  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: false
    hiddenInList: false
    hiddenInSingle: false

  editPost:
    URL: "https://github.com/yourusername/yourusername.github.io/tree/main/content"
    Text: "Suggest Changes"
    appendFilePath: true

  # Search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40
    - identifier: about
      name: About
      url: /about/
      weight: 50

# Taxonomies
taxonomies:
  category: categories
  tag: tags
  series: series

# Privacy settings
privacy:
  vimeo:
    disabled: false
    simple: true

  x:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

# Output formats
outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
