baseURL: "https://huangf06.github.io/GitStack/"
languageCode: en-us
title: "Bridging Worlds | 桥接世界"
theme: PaperMod

pagination:
  pagerSize: 10

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "Bridging Worlds | 桥接世界"
  description: "An intellectual journey bridging Eastern and Western thought through philosophy, literature, and personal reflections | 通过哲学、文学和个人反思连接东西方思想的智识之旅"
  keywords: [philosophy, literature, bilingual, essays, Kant, existentialism, 哲学, 文学, 双语, Rick and Morty, mental health]
  author: "Huang Fei"

  # Theme settings
  defaultTheme: auto # auto, light, dark
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: false
    disableFingerprinting: false
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"

  label:
    text: "Philosophy & Literature"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # Profile mode (for homepage)
  profileMode:
    enabled: true # Set to true for profile-style homepage
    title: "Bridging Worlds | 桥接世界"
    subtitle: |
      An intellectual journey across cultures
      一段跨越文化的智识之旅
    imageUrl: "" # Optional
    imageWidth: 120
    imageHeight: 120
    imageTitle: "Profile"
    buttons:
      - name: Essential Reads
        url: /essential/
      - name: Philosophy Journey
        url: /dialogues/
      - name: Timeline
        url: /timeline/

  # Home Info mode (alternative to profile mode)
  homeInfoParams:
    Title: "Welcome | 欢迎"
    Content: |
      > "The unexamined life is not worth living." - Socrates
      > "未经审视的生活不值得过。" - 苏格拉底

      An intellectual journey bridging Eastern and Western thought through philosophy, literature, and personal reflections.

      通过哲学、文学和个人反思连接东西方思想的智识之旅。

  socialIcons:
    - name: github
      url: "https://github.com/huangf06"
    - name: linkedin
      url: "https://linkedin.com/in/yourusername"
    - name: email
      url: "mailto:your.email@example.com"
    - name: rss
      url: "/index.xml"

  # Analytics (uncomment and configure when ready)
  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: false
    hiddenInList: false
    hiddenInSingle: false

  editPost:
    URL: "https://github.com/yourusername/yourusername.github.io/tree/main/content"
    Text: "Suggest Changes"
    appendFilePath: true

  # Search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: dialogues
      name: Dialogues | 对话
      url: /dialogues/
      weight: 10
    - identifier: reflections
      name: Reflections | 反思
      url: /reflections/
      weight: 20
    - identifier: critiques
      name: Critiques | 评论
      url: /critiques/
      weight: 30
    - identifier: journeys
      name: Journeys | 旅程
      url: /journeys/
      weight: 40
    - identifier: essential
      name: Essential | 精选
      url: /essential/
      weight: 50
    - identifier: timeline
      name: Timeline | 时间线
      url: /timeline/
      weight: 60
    - identifier: search
      name: Search | 搜索
      url: /search/
      weight: 70
    - identifier: about
      name: About | 关于
      url: /about/
      weight: 80

# Taxonomies
taxonomies:
  category: categories
  tag: tags
  philosopher: philosophers
  concept: concepts
  theme: themes

# Privacy settings
privacy:
  vimeo:
    disabled: false
    simple: true

  x:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

# Output formats
outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
