baseURL: "https://huangf06.github.io/FeiThink/"
title: "FeiThink"
theme: PaperMod
defaultContentLanguage: en
defaultContentLanguageInSubdir: true

languages:
  en:
    languageName: "English"
    languageCode: en-us
    weight: 1
    title: "FeiThink"
    params:
      description: "Personal blog about philosophy, technology, and life"
      profileMode:
        enabled: true
        title: "FeiThink"
        subtitle: "Thoughts on philosophy, technology, and life"
        buttons:
          - name: Posts
            url: /en/posts/
          - name: Archives
            url: /en/archives/
          - name: Tags
            url: /en/tags/
    menu:
      main:
        - identifier: posts
          name: Posts
          url: /en/posts/
          weight: 10
        - identifier: archives
          name: Archives
          url: /en/archives/
          weight: 20
        - identifier: tags
          name: Tags
          url: /en/tags/
          weight: 30
        - identifier: search
          name: Search
          url: /en/search/
          weight: 40
        - identifier: about
          name: About
          url: /en/about/
          weight: 50

  zh:
    languageName: "中文"
    languageCode: zh-cn
    weight: 2
    title: "飞想"
    params:
      description: "关于哲学、技术与生活的个人博客"
      profileMode:
        enabled: true
        title: "飞想"
        subtitle: "哲学、技术与生活的思考"
        buttons:
          - name: 文章
            url: /zh/posts/
          - name: 归档
            url: /zh/archives/
          - name: 标签
            url: /zh/tags/
    menu:
      main:
        - identifier: posts
          name: 文章
          url: /zh/posts/
          weight: 10
        - identifier: archives
          name: 归档
          url: /zh/archives/
          weight: 20
        - identifier: tags
          name: 标签
          url: /zh/tags/
          weight: 30
        - identifier: search
          name: 搜索
          url: /zh/search/
          weight: 40
        - identifier: about
          name: 关于
          url: /zh/about/
          weight: 50

pagination:
  pagerSize: 10

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  author: "Huang Fei"
  keywords: [blog, philosophy, technology, life, essays, writing, thinking]

  # Theme settings
  defaultTheme: auto # auto, light, dark
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: false
    disableFingerprinting: false
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"

  label:
    text: "FeiThink"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # Home Info mode (alternative to profile mode)
  homeInfoParams:
    Title: "Welcome to FeiThink"
    Content: |
      A place for exploring philosophy, technology, and the human experience.

      Feel free to explore my posts or browse by tags.

  socialIcons:
    - name: github
      url: "https://github.com/huangf06"
    - name: linkedin
      url: "https://linkedin.com/in/yourusername"
    - name: email
      url: "mailto:your.email@example.com"
    - name: rss
      url: "/index.xml"

  # Analytics (uncomment and configure when ready)
  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: false
    hiddenInList: false
    hiddenInSingle: false

  editPost:
    URL: "https://github.com/huangf06/FeiThink/tree/main/content"
    Text: "Suggest Changes"
    appendFilePath: true

  # Search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# Taxonomies
taxonomies:
  category: categories
  tag: tags
  series: series

# Privacy settings
privacy:
  vimeo:
    disabled: false
    simple: true

  x:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

# Output formats
outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
