baseURL: "https://huangf06.github.io/FeiThink/"
title: "FeiThink"
theme: PaperMod
defaultContentLanguage: en
defaultContentLanguageInSubdir: true

languages:
  en:
    languageName: "English"
    languageCode: en-us
    weight: 1
    title: "FeiThink"
    params:
      author: "Fei Huang"
      description: "Where mathematical rigor meets philosophical inquiry"
      profileMode:
        enabled: true
        title: "FeiThink"
        subtitle: "Bridging quantitative finance, AI, and philosophy"
        buttons:
          - name: Posts
            url: posts/
          - name: Archives
            url: archives/
          - name: Tags
            url: tags/
    menu:
      main:
        - identifier: posts
          name: Posts
          url: posts/
          weight: 10
        - identifier: archives
          name: Archives
          url: archives/
          weight: 20
        - identifier: tags
          name: Tags
          url: tags/
          weight: 30
        - identifier: search
          name: Search
          url: search/
          weight: 40
        - identifier: about
          name: About
          url: about/
          weight: 50

  zh:
    languageName: "中文"
    languageCode: zh-cn
    weight: 2
    title: "飞想"
    params:
      author: "黄飞"
      description: "数学精确与哲学深邃的交汇处"
      profileMode:
        enabled: true
        title: "飞想"
        subtitle: "连接量化金融、人工智能与哲学思考"
        buttons:
          - name: 文章
            url: posts/
          - name: 归档
            url: archives/
          - name: 标签
            url: tags/
    menu:
      main:
        - identifier: posts
          name: 文章
          url: posts/
          weight: 10
        - identifier: archives
          name: 归档
          url: archives/
          weight: 20
        - identifier: tags
          name: 标签
          url: tags/
          weight: 30
        - identifier: search
          name: 搜索
          url: search/
          weight: 40
        - identifier: about
          name: 关于
          url: about/
          weight: 50

pagination:
  pagerSize: 10

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  keywords: [quantitative finance, artificial intelligence, deep learning, reinforcement learning, philosophy, Kant, Dostoevsky, moral philosophy, trading strategies, uncertainty quantification]

  # Theme settings
  defaultTheme: auto # auto, light, dark
  disableThemeToggle: false
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: false
    disableFingerprinting: false
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"

  label:
    text: "FeiThink"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # Home Info mode (alternative to profile mode)
  homeInfoParams:
    Title: "Welcome to FeiThink"
    Content: |
      Where mathematical rigor meets philosophical depth.

      Exploring the intersections of quantitative finance, artificial intelligence, and moral philosophy.

  socialIcons:
    - name: github
      url: "https://github.com/huangf06"
    - name: linkedin
      url: "https://www.linkedin.com/in/fei-huang-9a7b5a1b7/"
    - name: email
      url: "mailto:huangf06@gmail.com"
    - name: rss
      url: "/index.xml"

  # Analytics (uncomment and configure when ready)
  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: false
    hiddenInList: false
    hiddenInSingle: false

  editPost:
    URL: ""
    Text: ""
    appendFilePath: false

  # Search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# Taxonomies
taxonomies:
  category: categories
  tag: tags
  series: series

# Privacy settings
privacy:
  vimeo:
    disabled: false
    simple: true

  x:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

# Output formats
outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
  page:
    - HTML
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  term:
    - HTML
    - RSS
